name: ci-mac

on: [push]

jobs:
  bootstrap:
    name: Bootstap on macOS using bootstrap.sh
    runs-on: macos-latest
    steps:
      - run: HOMEBREW_BUNDLE_CASK_SKIP HOMEBREW_BUNDLE_MAS_SKIP \
             curl -sf https://raw.githubusercontent.com/nothink/dotfiles/main/mac_bootstrap.sh | \
             sh -s
