name: ci-mac

on: [push]

jobs:
  bootstrap:
    name: Bootstap on macOS using bootstrap.sh
    runs-on: macos-latest
    steps:
      - run: curl -sf https://raw.githubusercontent.com/nothink/dotfiles/main/mac_bootstrap.sh | sh -s
